name: Deploy to Production

on:
  push:
    branches:
      - 'main'

jobs:
  all:
    name: CI/CD workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy Backend
        uses: JustArtiom/ptero-deploy@v1
        with:
          url: ${{ secrets.PTERO_URL }}
          api_key: ${{ secrets.PTERO_API_KEY }}
          server_id: f9b747ad
          clean: true
          run: |
            npm install
            node .